config/routes.rb
Rails.application.routes.draw do

  root      "top#index"
  get       "signup/",  to: "users#new"
  get       "login/",   to: "sessions#new"
  post      "login/",   to: "sessions#create"
  delete   "logout/",   to: "sessions#destroy"

  resources :users do
    member do
      get 'products'
    end
  end
  resources :account_activations,only: [:edit]
  resources :products
  resources :chat,only: [:create,:show]


end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token,:activation_token
  before_save :down_email
  before_create :create_activation_digest
  has_many :products,dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email,presence: true,uniqueness: true,format: {with: VALID_EMAIL_REGEX}

  validates :password,presence: true,length: { minimum: 6 },allow_nil: true

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest,User.digest(remember_token))
  end

  def authenticated?(attribute,token)
    digest = self.send("#{attribute}_digest") # ここでdiegest = :()_digestに変換している
    puts digest
    puts token
    return false if digest.nil?
    puts BCrypt::Password.new(digest)
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest,nil)
  end

  def down_email
    self.email = email.downcase
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(self.activation_token)
  end







  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :index, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy]

  def new
    @user = User.new
  end

  def index
    @users = User.paginate(page: params[:page])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.account_activation(@user).deliver_now
      flash[:info] = "Please check your email"
      redirect_to root_url
    else
      render "new"
    end
  end

  # ユーザープロフィールに関しての情報(名前など)
  def show
    @user = User.find_by(id: params[:id])
  end

  def products
    @user = User.find_by(id: params[:id])
    @products = Product.find_by(user_id: @user.id)
    unless @products.nil?
      @products = @products.order(created_at: :desc)
    end
  end
  
  def edit
    @user = User.find_by(id: params[:id])
  end
  
  def update
    @user = User.find_by(id: params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile Updated"
      redirect_to @user
    else
      render "edit"
    end
  end
  
  def destroy
    User.find_by(id: params[:id]).destroy
    flash[:success] = "Delete Complete"
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def correct_user
    @user = User.find_by(id: params[:id])
    redirect_to root_url unless current_user?(@user)
  end

  def admin_user
    redirect_to root_url unless current_user.admin?
  end

  #def edit_params
  #  params.require(:user).permit(:name,:email,:image,:introduction)
  #end
  
  
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end


end

app/views/users/_users.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    <%= link_to "Delete",user,method: :delete,data:{ confirm: "Sure?"} %>
  <% end %>
</li>

app/views/users/edit.html.erb
<h1>Update Your Profile</h1>
<div class="row">

  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>
      <%= render "shared/error_messages" %>
      <%= f.label :name %>
      <%= f.text_field :name,class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email,class: "form-control" %>

      <%= f.label :image %>
      <%= f.password_field :password,class: "form-control" %>

      <%= f.label :password_confirmation,"確認" %>
      <%= f.password_field :password_confirmation,class: "form-control" %>

      <%= f.submit "編集完了",class: "btn btn-primary" %>
    <% end %>


  </div>
</div>

<style>
  .row {
    text-align: center;
  }
  .col-md-6 {
    text-align: center;
  }
</style>

app/views/users/index.html.erb
<h1>All users</h1>

<% if @users %>

  <%= will_paginate  %>

  <ul class="users">
    <%= render @users %>
  </ul>

  <%= will_paginate  %>

<% end  %>

app/views/users/new.html.erb
<h1>Sign Up!</h1>
<div class="row">

  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>
      <%= render "shared/error_messages",object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name,class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email,class: "form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password,class: "form-control" %>

      <%= f.label :password_confirmation,"確認" %>
      <%= f.password_field :password_confirmation,class: "form-control" %>

      <%= f.submit "会員登録",class: "btn btn-primary" %>
    <% end %>


  </div>
</div>

<style>
  .row {
    text-align: center;
  }
  .col-md-6 {
    text-align: center;
  }
</style>

app/views/users/products.html.erb
<div class="container">
  <h1><%= @user.name %>の出品物一覧</h1>
  <% if not @products.nil? %>
  <%= will_paginate %>
  <div class="card-deck">
    <% @products.each do |product| %>
      <div class="card">
        <div class="card-header">
          <%= product.title %>
        </div>
        <div class="card-body">
          <h1 class="card-title"><%= product.price %></h1>
          <%= image_tag product.image.url %>
          <%= link_to "詳細画面", product_path(product) %>
        </div>
      </div>
    <% end %>
  </div>
  <%= will_paginate %>
<% else %>
  <h1 style="margin-top: 300px; text-align: center">出品物がありません。</h1>
<% end %>
</div>

app/views/users/show.html.erb
This is show html

<%= @user.name %>

<%= link_to "出品物情報",products_user_path(@user) %>