config/routes.rb
Rails.application.routes.draw do

  root      "top#index"
  get       "signup/",  to: "users#new"
  get       "login/",   to: "sessions#new"
  post      "login/",   to: "sessions#create"
  delete   "logout/",   to: "sessions#destroy"

  resources :users do
    member do
      get 'products'
    end
  end
  resources :account_activations,only: [:edit]
  resources :products
  resources :chat,only: [:create,:show]


end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  validates :user_id,presence: true
  validates :title,presence: true,length: {maximum: 30}
  validates :description,presence: true,length: {maximum: 300}
  # 自作のバリデーションの場合は単数形
  validate :product_image_size

  default_scope -> { order(created_at: :desc) }
  # 画像投稿の設定
  mount_uploader :image,ImageUploader

  def self.search(search)
    if search
      where(['title LIKE ?',"%#{search}%"]) # ここで出品名にキーワードを含む出品物を返す
    else
      all # 検索フォームからの値が存在しない場合は全て返す
    end
  end
  
  private

  def product_image_size
    if image.size > 5.megabytes
      errors.add(:image,"Should ne less than 5MB")
    end
  end





end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :logged_in_user,only:[:new,:create,:edit,:update,:destroy]
  before_action :equal_product_user,only: [:edit,:update,:destroy]

  # ここに検索機能を付け足す（自力で作成する）
  def index
    @products = Product.paginate(page: params[:page]).search(params[:search])
  end

  def new
    @product = current_user.products.new
  end

  def create
    @product = current_user.products.build(product_params)
    if @product.save
      flash[:success] = "商品を出品しました"
      redirect_to root_url
    else
      redirect_to root_url
    end
  end

  # リクエストURLから、パラメータを受け取り返す
  def show
    @product = Product.find_by(id: params[:id])
  end

  def edit
    @product = Product.find_by(id: params[:id])
  end

  def update
    if @product.update_attributes(product_params)
      flash[:success] = "商品情報の更新が完了しました"
      redirect_to root_url
    else
      redirect_to root_url
    end
  end

  def destroy
    Product.find_by(id: params[:id]).destroy
    flash[:success] = "出品物の削除が完了しました"
    redirect_to root_url
  end

  private

  def product_params
    params.require(:product).permit(:title,:description,:price,:category,:image)
  end

  # 商品を出品したユーザーのみ、編集・削除画面に移行できる
  # 現在ログインしているユーザーが、商品ページの出品者のIDと同じか判定する
  def equal_product_user
    @product = Product.find_by(id: params[:id])
    @user = User.find_by(id: @product.user_id)
    redirect_to root_url unless current_user?(@user)
  end



end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<h1>出品情報編集画面</h1>
<div class="container">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@product) do |f| %>
      <%= render "shared/error_messages",object: f.object %>

      <%= f.label :title %>
      <%= f.text_field :title,class: "form-control" %>

      <%= f.label :price %>
      <%= f.number_field :price,class: "form-control" %>

      <%= f.label :description %>
      <%= f.text_area :description,class: "form-control" %>

      <%= f.label :category %>
      <%= f.text_field :category,class: "form-control" %>

      <%= f.label :image %>
      <%= f.file_field :image,class: "form-control" %>

      <%= f.submit "編集完了",class: "btn btn-info" %>
    <% end %>

  </div>

</div>

app/views/products/index.html.erb
<% if @products.any? %>
  <%= will_paginate %>
  <div class="card-deck">
    <% @products.each do |product| %>
      <div class="card">
        <div class="card-header">
          <%= product.title %>
        </div>
        <div class="card-body">
          <h1 class="card-title"><%= product.price %></h1>
          <%= image_tag product.image.url %>
          <%= link_to "詳細画面", product_path(product) %>
        </div>
      </div>
    <% end %>
  </div>
  <%= will_paginate %>
<% else %>
  <h1 style="margin-top: 300px; text-align: center">出品物がありません。出品してください</h1>
<% end %>

app/views/products/new.html.erb
<h1>出品投稿画面</h1>
<div class="container">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@product) do |f| %>
      <%= render "shared/error_messages",object: f.object %>

      <%= f.label :title %>
      <%= f.text_field :title,class: "form-control" %>

      <%= f.label :price %>
      <%= f.number_field :price,class: "form-control" %>

      <%= f.label :description %>
      <%= f.text_area :description,class: "form-control" %>

      <%= f.label :category %>
      <%= f.text_field :category,class: "form-control" %>

      <%= f.label :image %>
      <%= f.file_field :image,class: "form-control" %>

      <%= f.submit "出品",class: "btn btn-info" %>
    <% end %>

  </div>

</div>

app/views/products/show.html.erb
<div class="container">
  <div class="row">
    <div class="card">
      <div class="card-title">
        <h1><%= @product.title %></h1>
      </div>
      <div class="card-body">
        <h1 class="card-title">値段：<%= @product.price %></h1>
        <ul class="list-unstyled">
          <li>出品者：<%= link_to "#{@product.user.name}",user_path(@product.user) %></li>
          <li>カテゴリ：<%= @product.category %></li>
          <li>説明：<%= @product.description %></li>
          <li>出品日:<%= @product.created_at %></li>
          <%= image_tag @product.image.url %>
        </ul>
        <% if current_user?(@product.user) %>
          <%= link_to "出品情報編集",edit_product_path(@product),class: "btn btn-success" %>
          <%= link_to "出品取り消し",product_path,method: :delete,class: "btn btn-danger" %>
        <% end %>
        <% unless current_user?(@product.user) %>

          <%= form_tag :chat_index,method: :post do %>
            <input type="hidden" name="seller_id" value="<%= @product.user.id %>">
            <input type="hidden" name="product_id" value="<%= @product.id %>">
            <%= submit_tag "DMを送る",class: "chatForm_btn" %>
          <% end %>

        <% end %>
      </div>

    </div>
  </div>

</div>