config/routes.rb
Rails.application.routes.draw do

  root      "top#index"
  get       "signup/",  to: "users#new"
  get       "login/",   to: "sessions#new"
  post      "login/",   to: "sessions#create"
  delete   "logout/",   to: "sessions#destroy"

  resources :users do
    member do
      get 'products'
    end
  end
  resources :account_activations,only: [:edit]
  resources :products
  resources :chat,only: [:create,:show]


end

app/views/layouts/_header.html.erb
<header>
  <div class="d-flex flex-column flex-md-row align-items-center p-5 px-md-4 mb-3 border-bottom shadow-sm"
  style="height: 100px">
    <h5 class="my-0 mr-md-auto font-weight-normal ml-5">
      <%= link_to "FreeMarket",root_path %>
    </h5>
    <%= form_tag(products_path,:method => "get",class: "form-inline mt-2 mt-md-0 mr-5") do %>
      <%= text_field_tag :search %>
      <%= submit_tag "Search",:name => nil ,class: "btn btn-outline-success my-2 my-sm-0" %>
    <% end %>

    <nav class="my-2 my-md-0 mr-md-3 ml-3">
      <%= link_to "出品一覧",products_path,class: "p-2" %>
      <%= link_to "カテゴリ","#",class: "p-2" %>
    </nav>
    <% if logged_in? %>
      <%= link_to "出品",new_product_path,class: "mr-3" %>
      <%= link_to "マイページ", user_path(current_user) %>
      <%= link_to "ログアウト",logout_path,method: :delete,class: "ml-3" %>
    <% else %>
      <%= link_to "新規登録",signup_path,class: "btn btn-outline-primary" %>
      <%= link_to "ログイン",login_path,class: "btn btn-outline-primary ml-3" %>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FreeMarket</title>
    <%= csrf_meta_tags %>
    <meta name="current_user_id" content="<%= current_user.id if current_user %>">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:success] %>
      <div class="flash-success">
        <%= flash[:success] %>
      </div>
    <% end %>
    <% if flash[:dander] %>
    <div class="flash-danger">
      <%= flash[:dander] %>
    </div>
  <% end %>
    <%= render "layouts/header" %>


    <%= yield %>

  </body>
</html>